apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubdemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubdemoapp
  template:
    metadata:
      labels:
        app: kubdemoapp
    spec:
      containers:
        - name: kubdemoapp
          image: siri2409/sample:kubeimage1   # use your Docker Hub image
          ports:
            - containerPort: 5000